version: '3'

services:
  oncall-web:
    build: .
    hostname: oncall
    ports:
      - "8080:8080"
    environment:
      - DOCKER_DB_BOOTSTRAP=1
      - IRIS_API_HOST=iris
    volumes:
      - ./configs/config.docker.yaml:/home/oncall/config/config.yaml
    networks:
      - iris
    depends_on:
      - oncall-mysql

  oncall-mysql:
    hostname: oncall-mysql
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    networks:
      - iris
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p1234"]
      interval: 10s
      timeout: 10s
      retries: 5

networks:
  iris:
    name: iris
